spring:
  profiles: local
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  data:
    elasticsearch:
      cluster-nodes: triber-todo-elastic:9300
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://triber-todo-discovery:8761/eureka/
