server:
  port: 0
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  jackson:
      serialization:
        write-dates-as-timestamps: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
