server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        command:
          destination: command.exchange
          group: command
          contentType: application/json
        event:
          destination: event.exchange
          contentType: application/json
      rabbit:
        bindings:
          command:
            consumer:
              durableSubscription: true
  jackson:
      serialization:
        write-dates-as-timestamps: false
