spring:
  profiles: local
  rabbitmq:
    host: localhost
    port: 5672
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
