server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: event
  cloud:
    stream:
      bindings:
        event:
          destination: event.exchange
          contentType: application/json
          group: event-store
      rabbit:
        bindings:
          event:
            consumer:
              durableSubscription: true
  jackson:
      serialization:
        write-dates-as-timestamps: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
