spring:
  profiles: local
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  rabbitmq:
    host: triber-todo-rabbit
    port: 5672
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://triber-todo-discovery:8761/eureka/
